version: '3.7'
services:
    db-NOME-PROJETO:
        container_name: db-NOME-PROJETO
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: NOME-PROJETO
            MYSQL_USER: NOME-PROJETO
            MYSQL_PASSWORD: NOME-PROJETO
        networks:
            - backend
    nginx:
        container_name: nginx-NOME-PROJETO
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - ./NOME-PROJETO:/var/www/NOME-PROJETO
            - ./nginx/logs/:/var/log/nginx
            - ./nginx/sites/:/etc/nginx/conf.d
            - ./nginx/data/ssl:/etc/nginx/ssl
        ports:
            - "443:443"
        networks:
            - backend

    php-fpm:
        container_name: php-fpm-NOME-PROJETO
        restart: always
        build:
            context: ./php-fpm
            dockerfile: Dockerfile
        expose:
            - "9000"
        volumes:
            - ./NOME-PROJETO:/var/www/NOME-PROJETO
        networks:
            - backend


networks:
    backend:
        driver: bridge
